services:
  static-app:
    container_name: libre-shield
    restart: always
    build: .
    volumes:
      - ./src/:/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.libreshield.rule=Host(`libreshield.untypequicode.fr`)
      - traefik.http.services.libreshield.loadbalancer.server.port=3000

      - homepage.group=Web
      - homepage.name=Libre Shield
      - homepage.icon=https://libreshield.untypequicode.fr/images/favicon.svg
      - homepage.href=https://libreshield.untypequicode.fr
      - homepage.siteMonitor=https://libreshield.untypequicode.fr
    ports:
      - 3000:3000
